### ISSUE TITLE
RIP: Rite of Moloch - Cohort SBT Factory

### ISSUE THREAD

**Issue by bitbeckers** [raid-guild/RIPs#114]
# RIP: Rite of Moloch - SBT

### Project Submitted By

st4rgard3n the 2ed
bitbeckers
benedictvs

## Summary

DAOs commit resources towards onboarding, while cohort participants often have little to no skin in the game. This can lead to wasteful outcomes, in terms of DAO resources and onboarding success rates.

Raid Guild has introduced an open source staking and soul bound token cohort dApp, for asynchronous onboarding and built to be interoperable for Moloch DAOs:

* The participants receive a soul bound token, after staking, and this token could be used to provide gated access to the cohort and resources.
* The staked assets are then forfeited if the user doesn’t complete the onboarding process. The individual cohort contracts are not upgradeable, but the cohort clone factory contract enables additional implementations to be added.

Currently the cohorts are specifically designed for Moloch DAOs and DAOHaus, but we can easily add new implementations for staking NFTs, or different membership criteria. Eventually, DAOs could deploy their own cohort clones, which require users to stake certain assets. 

## Why should we build this?

This is a breakdown of why you believe the Guild should spend resources to build this idea. Does it create revenue? Does it benefit the greater Eth ecosystem? Does it save humanity?

## Anything else you'd like to add?

Not at this time.

## Raid Party Skills Needed

- Frontend Developer: starrdev
- Smart Contract Developer: Huntrr
- Subgraph Developer: TBD, (bitbeckers assist if needed)
- Project Management & Design: benedictvs

## Deliverables

- As a DAO I want to cohort members to self-onboard through a staking mechanism.
- As a DAO, I want cohort members to receive an SBT to the address they used for staking.
- As a DAO, I want to replicate the staking and minting contracts from a factory to reliably provision new cohorts.
- As a DAO within the DAOHaus ecosystem, I want to use the Rite of Moloch factory as a plugin. 

### App
- [ ] Rite of Moloch frontend with web3 capabilities (Story points: ⭐️)
- [ ] Navigate to your active Rite(s) (Story points: ⭐️⭐️)
- [ ] Overview of rite and fail/success of participants (Story points: ⭐️)
- [ ] Basic SC interactions for the Rite flow (Story points: ⭐️⭐️)

### Graph
- [ ] Graph that tracks rites, stakes, participants (Story points: ⭐️⭐️⭐️)

### Contract
- [ ] Hats protocol integration with SC (Story points: ⭐️)
- [ ] Contract Factory that enables FE to spin up new instances of Rites (Story points: ⭐️)
- [ ] Plugin of rite factory to DAOHaus (Story points: ⭐️⭐️)

## Planning
It is expected to complete the RIP in eight weeks or four sprints with weekly checkins. The following work item specific workloads are expected:

- clone factory and deploying the seed - 30h
- frontend - 40h
- UI/ UX design - 20h
- subgraph - 26h
- DAOHaus integration - 40h
- collaboration, planning, documentation - 30h

TOTAL: 186h

## Cost (in USD)

Under the assumption that the hourly rate is USD 50, the project will cost RaidGuild a total of USD 9,300.00 with USD 6,975.00 to be paid in xDAI and USD 2,325.00 payable in RAID. The project is delivered as is with no time and material clause applicable.

### Provisions
The funds are to be released in two tranches after the successful completion of each milestone. To release the funds, the Raid Party for RIP #114 sets up a Gnosis Safe with which payment is requested through a funding proposal after the completion of a milestone. Fund distribution among Raid Party members is the done by the Raid Party by making transactions from the multi signature wallet. 

A grace period of one week is added to the date of delivery for the second milestone to finalise the work if needed and request the funds. Hence, the duration of the RIP is set to 9 weeks starting the day after a vote on this RIP has successfully passed on-chain voting of Raid Guild. All payments are due upon successful completion of the respective milestone and shall be dispersed using the Gnosis Network.

**Comment by bitbeckers** [comment]
### Milestone 1 - after 4 weeks: release of 0.75 x xDAI and 0.25 x RAID
* SG: Graph that tracks rites, stakes, participants
* UI: high fidelity wireframe for admin UI with components in Figma for: 
1. functionality to customise the SBT:
 a. upload 
 b. display
2. slash individual members 
3. release funds
* FE: stake raid and receive SBT, i.e. staking functionality
1. manual tests completed
2. deployed
* SC: Smart contracts checked and deployed sponsor or create a cohort.
* SC: Contract factory that enables frontend to spin up new instances of Rites.
* SC Hats protocol integration with smart contracts (Could be already there):
1. checked with starrgarden
2. deployed
* reworked staking page

**Comment by bitbeckers** [comment]
### Milestone 2 - after 8 weeks: release of 0.75 x xDAI and 0.25 x RAID
* UI & FE: admin UI component for analytics dashboard in Figma:
1. Rite Setup Page
2. Rite Management Page
a. Overview of rite and fail/ success of participants
b. track cohort members, 
c. individual rite performance, and,
d. performance of cohorts over time
e. slashing and releasing funds
* SC & SG: plugin of rite factory for DAOHaus
* SG, SC, FE, UI: testing, documentation

**Comment by plor** [comment]
Can we push this through the Kanban? Updating details where needed.

**Comment by plor** [comment]
I'm actually just going to close this. But updates on outcomes and references to funding proposals would be nice.

**Comment by benedictvscriticus** [comment]
##Team

@hking2 @sha256yan @personnamedmike @bitbeckers

## Description

In this scope of work we integrated RoM with DAOHaus v.3 for granting deployed cohorts permissions of manager Shaman and ensure usability. Furthermore, we implemented HATs protocol for permissions mapping of super administrators and delegates. These developments are based on the deployment of a Solidity contract factory for rapidly deployable cohorts. To make the technology stack accessible to users, we built subgraph integration to keep a light backend and access live data on the metrics dashboard, which were hooked to a new and extended frontend. We completed the RIP by deploying to Gnosis Chain Mainnet.

## Shipped features

- [x]  SG: Graph that tracks rites, stakes, participants
- [x]  UI: high fidelity wireframe for admin UI with components in Figma for
    - [x]  functionality to customise the SBT
        - [x]  upload
        - [x]  display
    - [x]  slash individual members
    - [x]  release funds
    - [x]  due 12/16/2022 @benedictvs
- [x]  FE: stake raid and receive SBT, i.e.
    - [x]  staking functionality
    - [x]  reworked staking page
    - [x]  Upgrade to RainbowKit and WAGMI
    - [x]  Refactor to Raid Guild Design-System
    - [x]  deploy cohort
    - [x]  manage cohort
        - [x]  placeholder for MS2 set
        - [x]  test transactions from SC required to display them on the page
        - [x]  will be finished next week for Wed January 18
    - [x]  attach FE to SC functionality
- [x]  SC: Smart contracts checked and deployed sponsor or create a cohort
- [x]  SC: Contract factory that enables frontend to spin up new instances of cohorts
- [x]  SC Hats protocol integration with smart contracts
    - [x]  one flow for ‘if the DAO has not yet a TOP HAT, creating TOP HAT and transforming it’
    - [x]  check with starrgarden to get feedback
    - [x]  deployed for DAO has not a TOP HAT yet
- [x]  we need to deploy the app at Vercel
- [x]  UI & FE: admin UI component for analytics dashboard in Figma
    - [x]  @benedictvs work can start immediately
    - [x]  Rite Setup Page
    - [x]  Rite Management Page
        - [x]  Overview of rite and fail/ success of participants
        - [x]  track cohort members,
            - [x]  track members of a specific cohort
            - [x]  track member irrespective of cohort (Shayan)
        - [x]  individual rite (cohort) performance (Shayan)
        - [x]  performance of cohorts over time
        - [x]  slashing and releasing funds
        - [x]  HAT transfer
        - [x]  adding administrators
- [x]  SC & SG: plugin of rite factory for DAOHaus
    - [x]  HATS Protocol update other flow ‘if DAO has TOP HAT, checking tree and building it backwards’ is MS 2
- [x]  SG, SC, FE, UI: testing, documentation

## Payouts

https://gnosisscan.io/tx/0x242e419ed66f876855a5e4ebc04e7b508a5105e8184870ad972d4022003e0ad9
https://gnosisscan.io/tx/0x90ad15cb97681ed136dd5c1704b4fe4bc7afb3364dd8ccfde1cf62ddaf127224
https://gnosisscan.io/tx/0x809a75d87402605dccc14354caeecf5ce663a0fa4e6607ab0d4b0446f7fe65c1
https://gnosisscan.io/tx/0x900b03068fe5d7e34dad4c0ea2e3e51b0b5ee9b81c16b938d269555ef40feb2e

**Comment by bitbeckers** [comment]
https://github.com/rite-of-moloch/
