### ISSUE TITLE
DM v2.2 - UX improvements

### ISSUE THREAD

**Issue by scottrepreneur** [raid-guild/RIPs#149]
### Project Submitted By

@derrekcoleman 
sayonara
0xmaker
scottrepreneur

### Milestone 1
*frontend*
- UI
  - [x] 	Add clarification to counts on the several pages
  - [x] 	Change default member view to "actively raiding"
  - [x] 	Remove Dashboard heading on /
  - [x] 	Change "Add Role" to "Add Role Required" dropdown copy. stack if buttons too wide.
  - [x] 	Copy Raid ID button
    		- Clean up width/truncate (to number of lines with Chakra)
  - [x] 	Show Project Specs when no link is available. provide default "partial" line 108 of RaidDetailsCard.tsx
  - [x] 	`InfoStack` with link is different size/font to text infos
  - [x] 	Min Width on Consultation/Raid Details section(s)
  - [x] 	Specs value is missing or missing NA option 
  - [x] 	Better status update layout
  - [x] 	Hide nav links unless logged in

- UX
   - [x] Allow users to remove "Role Needed" from raid. (solved by existing multi-select feature request)
     - https://github.com/raid-guild/dungeon-master-v2/issues/71
   - [ ]  Check oldest/recent comment sort
     - Close but not quite working

*backend*
- [x] Links to Raid M2M table
- [x] Add Hunter to Raid table (like Cleric)
- [x] Add interest to raid/consultation M2M table

*ux*
- [x] Raid Edit Form (inc. add Project Specs link)
- [x] Dashboard UX
- [x] Raid Card IA on "Raids" list (research improvements)

~1.5 ETH

### Milestone 2
*frontend*
UI
- [x] Make Cards clickable (Link Overlay). box shadow, remove View Details.
     - [x] 	Raid
     - [x] 	Consultation
     - [x] 	Member
     - [x] 	Application
     - [x]     RIP
- [ ] Add tooltip for role badges
- [ ] Better Stack for Raid Party on Raid Cards. vertical with overlap just like Roles Required. bottom of Raid Party is same height as bottom of Last Status Update.
- [x] Redirect logged out routes to dashboard

UX
- [ ] Allow users to edit their profile info
     - [ ] `isRaiding`
     - [ ] 	Bio
     - [ ] 	Primary/Secondary Skills
- [ ] Add the ability to edit more data on the raid and consultations
     - [ ] 	Description
- [ ] Add a retrospective to the process of completing a raid
- [ ] Add the ability to add links to raid assets
- [ ] Add the ability to signal interest in a raid
- [ ] Consistent dashboard no matter raids
     - Better dashboard for new (0 raid) folks

~1.25 ETH

### Milestone 3
*frontend*
- [ ] Update Accounting to v3 DAO
- [ ] Show Smart Escrow & spoils updates
- [ ] Check for expiring token and issue a new one [Ref](https://stackoverflow.com/questions/67287620/nextauth-hasura-refresh-token) [Ref2](https://github.com/nextauthjs/next-auth/issues/371)
- [ ] Show portfolio data on the Raid details page
- [ ] Allow clerics/users to create and edit portfolio records
- [ ] Prompt user to add portfolio record when raid marked as shipped

~0.75 ETH

**Total**
3.5 ETH
5 - 7 weeks to Design, Dev & QA [2, 2, 2] 

## Why should we build this?

Driving value through our central tool will continue to reap benefits as we ramp up Raid processing again. Paired with #148 will accelerate our efforts.

## Anything else you'd like to add?

Not at this time.

## Raid Party Skills Needed

- UX
- PM
- Builder

## Cost (in USD)

3.25 ETH

**Comment by derrekcoleman** [comment]
scott done with backend, sayonara almost done with design, derrek almost done with frontend. ETD soon™️

**Comment by scottrepreneur** [comment]
### Milestone 1 Update

ux
- [Raid Card updates](https://www.figma.com/file/tPkMa4TI1kD7iFJmOLuKaN/RaidGuild-DSM-(RG-UI)?type=design&node-id=545-12193&mode=design&t=OUhaCv7fHDTLZ3g2-0)
  
  <img width="630" alt="Screenshot 2023-11-02 at 12 22 54" src="https://github.com/raid-guild/RIPs/assets/1778380/a50f4d69-7164-42cc-9702-3c3570551275">


- [Raid Form updates](https://www.figma.com/file/tPkMa4TI1kD7iFJmOLuKaN/RaidGuild-DSM-(RG-UI)?type=design&node-id=623-18225&mode=design&t=Akwf5GiayeRtM3Ht-0)
  
  <img width="883" alt="Screenshot 2023-11-02 at 12 21 26" src="https://github.com/raid-guild/RIPs/assets/1778380/8354e765-3098-46e5-a51a-4aa3c66559e8">


- [Dashboard](https://www.figma.com/file/tPkMa4TI1kD7iFJmOLuKaN/RaidGuild-DSM-(RG-UI)?type=design&node-id=628-20660&mode=design&t=nniXxZohoNKEw1uZ-0)
   
   <img width="499" alt="Screenshot 2023-11-02 at 12 20 17" src="https://github.com/raid-guild/RIPs/assets/1778380/32ffda54-759b-4715-b90b-eb390ec46f8a">



backend
- [PR on DM](https://github.com/raid-guild/dungeon-master-v2/pull/87)
- Links to Raid M2M table
- Add Hunter to Raid table (like Cleric)
- Add interest to raid/consultation M2M table

frontend
- [PR on DM](https://github.com/raid-guild/dungeon-master-v2/pull/89)
- Add clarification to counts on the several pages
- Change default member view to "actively raiding"
- Remove Dashboard heading on /
- Change "Add Role" to "Add Role Required" dropdown copy. stack if buttons too wide.
- Copy Raid ID button
	- Clean up width/truncate (to number of lines with Chakra)
- Show Project Specs when no link is available. provide default "partial" line 108 of RaidDetailsCard.tsx
- `InfoStack` with link is different size/font to text infos
- Min Width on Consultation/Raid Details section(s)
- Specs value is missing or missing NA option
- Better status update layout
- Hide nav links unless logged in

**Comment by derrekcoleman** [comment]
_.sayonara coded the UI/UX [for most of milestone 2](https://discord.com/channels/684227450204323876/1153373446915502220/1181190356759490640). He's working on integration with backend and testing.

**Comment by derrekcoleman** [comment]
Milestone 2 is live on dm.raidguild.org! Everyone can edit raid fields and signal interest on raids. Updated PFPs. Added ability to add a Hunter (like a Cleric). Escrow lets you deploy a safe and split at the same time.

**Comment by memosys** [comment]
Milestone 2 Updates
1. Better Dashboard with ability to signal Interest on Raids and Consultations

<img width="1328" alt="Screenshot 2024-01-06 at 12 35 04 AM" src="https://github.com/raid-guild/RIPs/assets/82053242/fa51834b-7222-461f-8ed9-029744a928f8">

<img width="1264" alt="Screenshot 2024-01-06 at 12 29 40 AM" src="https://github.com/raid-guild/RIPs/assets/82053242/b889ee0a-ad92-4e03-985e-ef09befde3a2">

2. Abilitiy to edit Self-Information for Members
<img width="772" alt="Screenshot 2024-01-06 at 12 30 38 AM" src="https://github.com/raid-guild/RIPs/assets/82053242/3f006f6a-084e-47f1-bad3-ddd9d9eedc43">

3. New Design for Raid Cards, and Avatars pulled from member info
<img width="1238" alt="Screenshot 2024-01-06 at 12 31 10 AM" src="https://github.com/raid-guild/RIPs/assets/82053242/899c355e-9227-4072-8c73-1d8a5ff9bd85">

4. Updated Raid Details, with Multiple Contact, Key Link Support
<img width="748" alt="Screenshot 2024-01-06 at 12 36 36 AM" src="https://github.com/raid-guild/RIPs/assets/82053242/bb45e72c-33d2-4ead-b20d-d0a237a7ff40">

5. Edit More Raid Information
<img width="596" alt="Screenshot 2024-01-06 at 12 36 48 AM" src="https://github.com/raid-guild/RIPs/assets/82053242/49ac2f64-e909-4cfc-a66d-eb01156c20f2">
<img width="662" alt="Screenshot 2024-01-06 at 12 36 54 AM" src="https://github.com/raid-guild/RIPs/assets/82053242/b86d81ad-81f8-4446-a6c9-a0ccbd87cfcf">

6. See Interested Members on Raid Details Page
<img width="449" alt="Screenshot 2024-01-06 at 12 38 55 AM" src="https://github.com/raid-guild/RIPs/assets/82053242/844a63ed-c405-4525-8fe5-446c0f7bd4aa">

& Other Escrow Updates by @scottrepreneur

**Comment by scottrepreneur** [comment]
Milestone 2 has been released

**Comment by ECWireless** [comment]
There was an issue updating the accounting page for Moloch v3. May need to be punted to a separate RIP if it proves too difficult.

**Comment by derrekcoleman** [comment]
Rowdy has an implementation for the jwt renewal but needs to sync up with Scott to go over it.

**Comment by memosys** [comment]
1. Show Smart Escrow & spoils updates
![Screenshot 2024-04-09 at 11 25 37 PM](https://github.com/raid-guild/RIPs/assets/82053242/93b5e988-cc04-48b2-a247-92e0c8b34694)
2.  Check for expiring token and issue a new one
- Done by rowdy via https://github.com/raid-guild/dungeon-master-v2/pull/113
3. Show portfolio data on the Raid details page
![Screenshot 2024-04-09 at 11 29 43 PM](https://github.com/raid-guild/RIPs/assets/82053242/6ec3a405-c8a5-42a6-bdca-998517440e0b)
4. Allow clerics/users to create and edit portfolio records
![Screenshot 2024-04-09 at 11 30 45 PM](https://github.com/raid-guild/RIPs/assets/82053242/86585f8c-253e-45c8-aff4-909a9028d334)
5. Prompt user to add portfolio record when raid marked as shipped
on click -> SHIPPED `status` you will get a second pop-up and have to provide a retro link
![Screenshot 2024-04-09 at 11 31 58 PM](https://github.com/raid-guild/RIPs/assets/82053242/2f383868-cf75-4e0d-8af6-41285418de85)
